// set up seats array
//altered seats array so that they have values availability set to true or false
const seats = [
  { seat: "A1", available: true },
  { seat: "A2", available: true },
  { seat: "A3", available: true },
  { seat: "A4", available: true },
  { seat: "A5", available: true },
  { seat: "A6", available: true },
  { seat: "A7", available: true },
  { seat: "A8", available: true },
  { seat: "A9", available: true },
  { seat: "A10", available: true },
  { seat: "B1", available: true },
  { seat: "B2", available: true },
  { seat: "B3", available: true },
  { seat: "B4", available: true },
  { seat: "B5", available: true },
  { seat: "B6", available: true },
  { seat: "B7", available: true },
  { seat: "B8", available: true },
  { seat: "B9", available: true },
  { seat: "B10", available: true },
  { seat: "C1", available: true },
  { seat: "C2", available: true },
  { seat: "C3", available: true },
  { seat: "C4", available: true },
  { seat: "C5", available: true },
  { seat: "C6", available: true },
  { seat: "C7", available: true },
  { seat: "C8", available: true },
  { seat: "C9", available: true },
  { seat: "C10", available: true },
  { seat: "D1", available: true },
  { seat: "D2", available: true },
  { seat: "D3", available: true },
  { seat: "D4", available: true },
  { seat: "D5", available: true },
  { seat: "D6", available: true },
  { seat: "D7", available: true },
  { seat: "D8", available: true },
  { seat: "D9", available: true },
  { seat: "D10", available: true },
  { seat: "E1", available: true },
  { seat: "E2", available: true },
  { seat: "E3", available: true },
  { seat: "E4", available: true },
  { seat: "E5", available: true },
  { seat: "E6", available: true },
  { seat: "E7", available: true },
  { seat: "E8", available: true },
  { seat: "E9", available: true },
  { seat: "E10", available: true },
  { seat: "F1", available: true },
  { seat: "F2", available: true },
  { seat: "F3", available: true },
  { seat: "F4", available: true },
  { seat: "F5", available: true },
  { seat: "F6", available: true },
  { seat: "F7", available: true },
  { seat: "F8", available: true },
  { seat: "F9", available: true },
  { seat: "F10", available: true },
];

$(document).ready(function () {
  seats.forEach((seat) => {
    $("#seats-wrapper").append(`<div class="seat">${seat.seat}</div>`);
  });
});
